name: Update Readme

on:
  workflow_dispatch: # manual trigger
  schedule:
    - cron: '0 12 * * *' # runs daily at 12:00 UTC

jobs:
  update-readme:
    runs-on: ubuntu-latest
    steps:
      # Step 1: Checkout the repo
      - name: Checkout Repo
        uses: actions/checkout@v3

      # Step 2: Update GitHub Activity Section
      - name: Update GitHub Activity
        uses: jamesgeorge007/github-activity-readme@master
        env:
          GITHUB_TOKEN: ${{ secrets.GH_TOKEN }}

      # Step 3: Update WakaTime Stats
      - name: Update WakaTime Stats
        uses: anmol098/waka-readme-stats@master
        with:
          COMMIT_BY_ME: "False"
          COMMIT_MESSAGE: "Updated dev metrics"
          COMMIT_USERNAME: "Farhadul Islam"
          COMMIT_EMAIL: "farhadulislam84054@gmail.com"
          WAKATIME_API_KEY: ${{ secrets.WAKATIME_API_KEY }}
          GH_TOKEN: ${{ secrets.GH_TOKEN }}
          SHOW_OS: "False"
          SHOW_PROJECTS: "True"
          SHOW_UPDATED_DATE: "True"
          SHOW_PROFILE_VIEWS: "False"
          SHOW_EDITORS: "False"
          SHOW_LANGUAGE: "True"
          SHOW_LANGUAGE_PER_REPO: "False"
          SHOW_LINES_OF_CODE: "True"
          SHOW_COMMIT: "True"
          SHOW_LOC_CHART: "False"
          SHOW_DAYS_OF_WEEK: "False"
          SHOW_SHORT_INFO: "True"

      # Step 4: Update Simple WakaTime Stats
      - name: Update WakaTime Simple
        uses: guilyx/waka-readme@master
        with:
          WAKATIME_API_KEY: ${{ secrets.WAKATIME_API_KEY }}
          GH_TOKEN: ${{ secrets.GH_TOKEN }}
          SECTION_NAME: "waka-simple"
          COMMIT_MESSAGE: "Updated simple WakaTime stats section"
          BLOCKS: "⣀⣄⣤⣦⣶⣷⣿"
          TIME_RANGE: all_time
          SHOW_TIME: true
          SHOW_MASKED_TIME: true
          SHOW_TITLE: true
